### ISSUE TITLE
Expose filtering?

### ISSUE THREAD

**Issue by HeyHugo** [adamchainz/django-watchfiles#2]
Nice work!

Would it make sense to expose [filtering of files that are watched](https://github.com/samuelcolvin/watchfiles#custom-filters), possibly via some setting? Maybe some regexp list or pointing to a custom filtering class to use.

I tried this out in a project with a sqlite db (where the db-file was in the source root). On db writes the application would restart 🙃

**Comment by adamchainz** [comment]
Django already provides some information on which files to watch, this project just needs to use that. I don't think it needs to expose extra settings.

**Comment by HeyHugo** [comment]
Aha I see, makes sense 👍
