### ISSUE TITLE
HTML reload with django-browser-reload does not work

### ISSUE THREAD

**Issue by Tobi-De** [adamchainz/django-watchfiles#69]
### Python Version

3.11.5

### Django Version

5.0.1

### Package Version

0.1.1

### Description

When both django-watchfiles and django-browser-reload are installed, changes to HTML files no longer trigger a browser reload, while Python files still cause the server to reload. The issue can be replicated using this repository: https://github.com/Tobi-De/broken_html_reload. There is a `requirements.txt` file at the root of the project if you prefer not to use Hatch.

By default, you will observe that any modifications to HTML files do not trigger a server reload. However, if you comment out django-watchfiles, everything works as expected. It's worth noting that changes to Python files still result in a server reload, whether or not django-watchfiles is present.

**Comment by adamchainz** [comment]
Thanks for testing this alpha-level package. When I find time to work on it more, I’ll look at your issue directly.

Off the top of my head, there should be no reason why HTML files don’t trigger a reload. This package passes watchfiles all the file names that Django requests watching, including templates.

**Comment by kstypik** [comment]
Can confirm this. @adamchainz could this be related with the templates being cached by default since 4+1? https://nickjanetakis.com/blog/django-4-1-html-templates-are-cached-by-default-with-debug-true

**Comment by Tobi-De** [comment]
This is actually fixed on my end, I'm not sure when and how this happened, but this is no longer an issue for me.
I've switched from watchman to this, especially now that it got harder to install the latest version of watchman on linux (no more prebuilt binaries for the latest version).
@adamchainz maybe this should be recommended in django boost your dx over watchman, just a suggestion

**Comment by adamchainz** [comment]
I will recomend it in the book, when I find time to finish off the package first.
