### ISSUE TITLE
An option to change debug mode

### ISSUE THREAD

**Issue by ddahan** [adamchainz/django-watchfiles#9]
Is there a way to change the default verbosity when using Django watchfiles?
I'd like to remove these lines:
```
watcher: INotifyWatcher { channel: Sender { .. }, waker: Waker { inner: Waker { fd: File { fd: 7, path: "anon_inode:[eventfd]", read: true, write: true } } } }
raw-event: Event { kind: Modify(Data(Any)), paths: ["/workspaces/mango/diagram.puml"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None }
```

Thanks.

**EDIT**: I found a workaround by:
- installing `watchfiles` as a dependency package
- cloning your app into my source code (to make it my own app)
- changing `watcher = watchfiles.watch(*roots, debug=True)` to `watcher = watchfiles.watch(*roots, debug=False)`

It works but it would be great to have a config option directly from settings :)

**Comment by adamchainz** [comment]
This is still alpha software - when I have the time to finish it off, I'll work on setting the level appropriately, hopefully based on the `runserver` command's verbosity levele.

**Comment by adamchainz** [comment]
The debug flag was dropped in dc1af91876a6a7d6311268f23088fb83657df7c9, so I think this doesn't occur any more.
